export const dynamic = "force-dynamic";

import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Prevent flash of wrong theme on first load */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('aicruiter-theme');var d=window.matchMedia('(prefers-color-scheme: dark)').matches;if(t==='dark'||(t===null&&d)){document.documentElement.classList.add('dark')}}catch(e){}})();`,
          }}
        />
      </head>
      <body

        >
          

         <ClerkProvider>

           <Provider>



        {children}

        </Provider>
         </ClerkProvider>
    
       
      </body>
    </html>
  );
}
